#|
    The sine of an angle (specified in radians) can be computed by making use of the approximation sin x ≈ x if x is sufficiently small, and the trigonometric identity

    sin x = 3*sin(x/3) - 4*sin^3(x/3)

    to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered sufficiently small if its magnitude is not greater than 0.1 radians.) 
    These ideas are incorporated in the following procedures:

    (define (cube x) (* x x x))

    (define (p x) (- (* 3 x) (* 4 (cube x))))
    
    (define (sine angle)
        (if (not (> (abs angle) 0.1))
            angle
            (p (sine (/ angle 3.0)))))

    1.  How many times is the procedure p applied when (sine 12.15) is evaluated?
    2.  What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated? 
 |#

 1.
    (sine 12.15)
    (p (sine (/ 12.15 3))) ; 4.04
    (p (p (sine (/ 4.04 3)))) ; 1.34
    (p (p (p (sine (/1.34 3))))) ; 0.448
    (p (p (p (p (sine (/0.448 3)))))) ; 0.149
    (p (p (p (p (p (sine (/0.149 3))))))) ; 0.049 is less than 0.1, so p is executed 5 times.

2. 
;  On each step angle value is devided by 3 until the angle value reaches approximately 0.1 This can be written as

;  angle / 3^n ≈ 0.1 or 3^n ≈ angle / 0.1

;  To calculate n we must calculate a logarithm of angle / 0.1 on base 3 

;  n = log3 (angle/0.1)

;  So the order of growth of steps is logarithmic O(log n). On each step the space is icreasing by 1, so the order of growth of space is also O(log n).