#|
    1. Draw the tree illustrating the process generated by the count-change procedure in making change for 11 cents. 
    
    (define (count-change amount)
        (cc amount 5))
    (define (cc amount kinds-of-coins)
        (cond ((= amount 0) 1)
              ((or (< amount 0) (= kinds-of-coins 0)) 0)
              (else (+ (cc amount
                           (- kinds-of-coins 1))
                       (cc (- amount
                              (first-denomination kinds-of-coins))
                           kinds-of-coins)))))
    (define (first-denomination kinds-of-coins)
        (cond ((= kinds-of-coins 1) 1)
              ((= kinds-of-coins 2) 5)
              ((= kinds-of-coins 3) 10)
              ((= kinds-of-coins 4) 25)
              ((= kinds-of-coins 5) 50)))

    2. What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?

    Answer:
    1. The image of tree illustrating the process is saved in ex_1.14_tree.png. I have replaced some dublicated branches with (...), 
    which can be found in the sibling or child branches of the tree. 

           count-change 11
                 |
              cc 11 5
              /      \
             /        \
    cc (- 11 50) 5    cc 11 4
          /          /       \
         0   cc (- 11 25) 4   cc 11 3
                  /          /       \
                 0          /         \
             _____________ /           \
            /                           \
    cc (- 11 10) 3                      cc 11 2
        /    \                           /    \________
    cc -9 3  cc 1 2                  cc 6 2         cc 11 1
     /      /    \                    /   \         /     \
    0   cc -4 2   cc 1 1        cc 1 2   cc 6 1   cc 10 1  cc 11 0
          /       /  \             /       |       |         \
         0   cc 0 1   cc 1 0     ...      ...      |           0
               /       \         [1]      [1]     / \
             [1]        0                        /   \_____
                                           cc 10 1       cc 11 0
                                            /    \           \
                                        cc 9 1   cc 10 0       0
                                        /   \      \
                                   cc 8 1  cc 9 0   0
                                    /   \      \
                                cc 7 1  cc 8 0   0
                                /   \      \
                            cc 6 1  cc 7 0   0
                            /   \      \
                         cc 5 1  cc 6 0   0
                         /   \      \
                     cc 4 1  cc 5 0   0
                      /   \      \
                 cc 3 1  cc 4 0   0
                  /   \      \
             cc 2 1  cc 3 0   0
              /   \      \
         cc 1 1  cc 2 0   0
          /   \      \
     cc 0 1  cc 1 0   0
       /        \
      [1]        0

  2.1 The space grows linearly to the amount to be changed, which is visualized by the longest branch of the tree. 
  So the order of growth of space is O(n).

  2.2 Number of steps  
  I have updated the count-change procedure and added a counter of execution of cc procedure.
  
  Results of running count-change:
  count-change 1 – 6
  count-change 5 – 15
  count-change 10 – 36
  count-change 25 – 200
  count-change 50 – 1199
  count-change 100 – 11284

  In ex_1.14_graphics.png those results are shown on a graph. The curve is exponential, so i assume that the order of growth of steps is O(n^y), 
  where n is the change amount and y is the value of kinds of coins.
 |#